language: go

go:
  - "1.10.x"

before_script:
  - go vet -printf ./...

install:
  # Add Godeps dependencies to GOPATH and PATH
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure